"""create lobby table 

Revision ID: 553f019aff3a
Revises: 1e3c1e36de63
Create Date: 2025-07-12 19:08:05.782484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '553f019aff3a'
down_revision: Union[str, Sequence[str], None] = '1e3c1e36de63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_players', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_players', 'status')
    # ### end Alembic commands ###
