"""update role enum in user table

Revision ID: 626414ceb66f
Revises: 
Create Date: 2025-07-06 11:26:44.319691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '626414ceb66f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('score', sa.BigInteger(), nullable=True))
    op.drop_column('users', 'ranking_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ranking_rate', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'score')
    # ### end Alembic commands ###
