"""update role enum in user table

Revision ID: 7f321c870653
Revises: 
Create Date: 2025-07-11 23:15:05.004973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f321c870653'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lobbies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('host_user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('max_items_per_player', sa.Integer(), nullable=True),
    sa.Column('initial_hand_size', sa.Integer(), nullable=True),
    sa.Column('match_time_sec', sa.Integer(), nullable=True),
    sa.Column('player_count_limit', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_lobbies_id'), 'lobbies', ['id'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('order_code', sa.BigInteger(), nullable=False),
    sa.Column('payos_payment_id', sa.String(length=255), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', 'EXPIRED', name='paymentstatus'), nullable=False),
    sa.Column('checkout_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payos_reference', sa.String(length=255), nullable=True),
    sa.Column('payos_account_number', sa.String(length=50), nullable=True),
    sa.Column('transaction_datetime', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=True)
    op.create_index(op.f('ix_payments_order_code'), 'payments', ['order_code'], unique=True)
    op.create_index(op.f('ix_payments_payos_payment_id'), 'payments', ['payos_payment_id'], unique=False)
    op.drop_index(op.f('ix_payment_orders_id'), table_name='payment_orders')
    op.drop_table('payment_orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_orders',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('order_code', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expired_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('payment_link_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('payment_orders_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payment_orders_pkey'))
    )
    op.create_index(op.f('ix_payment_orders_id'), 'payment_orders', ['id'], unique=True)
    op.drop_index(op.f('ix_payments_payos_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_code'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_lobbies_id'), table_name='lobbies')
    op.drop_table('lobbies')
    # ### end Alembic commands ###
