"""update rr in user table

Revision ID: 83949237187f
Revises: 4f964a55e3ae
Create Date: 2025-06-30 15:55:37.296840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83949237187f'
down_revision: Union[str, Sequence[str], None] = '4f964a55e3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ranking_rate', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ranking_rate')
    # ### end Alembic commands ###
