"""delete unique lobby code

Revision ID: 8597ed2c4212
Revises: f05b0887931c
Create Date: 2025-07-14 02:14:44.451489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8597ed2c4212'
down_revision: Union[str, Sequence[str], None] = 'f05b0887931c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lobbies_code_key'), 'lobbies', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('lobbies_code_key'), 'lobbies', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
