"""delete question from card

Revision ID: f05b0887931c
Revises: 553f019aff3a
Create Date: 2025-07-13 20:44:41.966121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f05b0887931c'
down_revision: Union[str, Sequence[str], None] = '553f019aff3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cards_question_id_fkey'), 'cards', type_='foreignkey')
    op.drop_column('cards', 'question_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('cards_question_id_fkey'), 'cards', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
